import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <a href="/" className="fixed top-4 left-4 p-2 font-bold text-lg bg-red-100 rounded-full w-12 h-12 flex items-center justify-center hover:bg-red-200 transition-colors z-50">
          <span className="whitespace-nowrap">ㅐㅇㅆㅌ</span>
        </a>
        <div className="mx-auto max-w-2xl px-4 pt-8">
          <div className="border border-solid border-red-100 pt-4 px-6 pb-6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
